/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import app.MessageType;
import component.popMix;
import static component.popMix.splitByteArray;
import event.EventMenuRight;
import event.PublicEvent;
import io.socket.client.Ack;

import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileFilter;
import main.Main;
import model.Model_Package_Sender;
import model.Model_Send_Message;
import model.Model_User_Account;
import swing.FileChooser;

/**
 *
 * @author Admin
 */
public class Menu_Right extends javax.swing.JPanel {

    /**
     * @param fileSize the fileSize to set
     */
    public void setFileSize(long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * @return the bb
     */
    public ByteBuffer getBb() {
        return bb;
    }

    /**
     * @param bb the bb to set
     */
    public void setBb(ByteBuffer bb) {
        this.bb = bb;
    }

    /**
     * @return the DataByte
     */
    public byte[] getDataByte() {
        return DataByte;
    }

    /**
     * @param DataByte the DataByte to set
     */
    public void setDataByte(byte[] DataByte) {
        this.DataByte = DataByte;
    }
    /**
     * Creates new form Menu_Left
     */
    public Menu_Right() {
        initComponents();
        
       PublicEvent.getInstance().addEventMenuRight(new EventMenuRight() {
            @Override
            public void setImageAvatar(Model_User_Account user) {
                ByteArrayInputStream bis = new ByteArrayInputStream(user.getImage());
                try {
                    BufferedImage bImage = ImageIO.read(bis);
                    ImageIcon Avatar = new ImageIcon(bImage);
                    imaAvatar.setImage(Avatar);
                    imaAvatar.repaint();
                    imaAvatar.revalidate();
                } catch (IOException ex) {
                    Logger.getLogger(Menu_Right.class.getName()).log(Level.SEVERE, null, ex);
                }
                userName.setText("Welcome "+user.getUserName()+" !");
         
                }
        });
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel2 = new javax.swing.JLayeredPane();
        imaAvatar = new swing.ImageAvatar();
        panel1 = new swing.Panel();
        userName = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(249, 249, 249));

        imaAvatar.setBorderColor(new java.awt.Color(107, 13, 158));
        imaAvatar.setBorderSize(2);
        imaAvatar.setImage(new javax.swing.ImageIcon(getClass().getResource("/icon/profile2.png"))); // NOI18N
        imaAvatar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imaAvatarMouseClicked(evt);
            }
        });

        panel1.setBackground(new java.awt.Color(26, 1, 26));

        userName.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("Hello Phuc !");
        panel1.add(userName);
        userName.setBounds(20, 0, 140, 40);

        jButton1.setBackground(new java.awt.Color(220, 53, 69));
        jButton1.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Đăng xuất");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Panel2.setLayer(imaAvatar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Panel2.setLayer(panel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Panel2.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout Panel2Layout = new javax.swing.GroupLayout(Panel2);
        Panel2.setLayout(Panel2Layout);
        Panel2Layout.setHorizontalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel2Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(imaAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel2Layout.setVerticalGroup(
            Panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(imaAvatar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void imaAvatarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imaAvatarMouseClicked
       if (evt.getClickCount() == 2 && SwingUtilities.isLeftMouseButton(evt)) {
          JFileChooser ch = new JFileChooser();
                 FileChooser preview = new FileChooser();
                 ch.setAccessory(preview);
                 ch.addPropertyChangeListener(preview);
                 ch.setFileFilter(new FileFilter(){
                     @Override
                     public boolean accept(File file) {
                            return file.isDirectory()||isImageFile(file);
                         }

                     @Override
                     public String getDescription() {
                            return "Image File";
                         }
                     
                 });
                 int option = ch.showOpenDialog(Main.getFrames()[0]);
                  if (option == JFileChooser.APPROVE_OPTION){
                        File file = ch.getSelectedFile();
                        ImageIcon image = new ImageIcon(ch.getSelectedFile().getAbsolutePath());                       
                        imaAvatar.setImage(image);
  
                        imaAvatar.repaint();
                        imaAvatar.revalidate();    
                         
                try {
                        FileInputStream in = new FileInputStream(file);
                        byte data[] = new byte[in.available()];
                        this.setDataByte(data);
                        in.read(data);
                        in.close();
                        this.setBb(ByteBuffer.wrap(data));
                        this.setFileSize(bb.limit());
                        
                        // Update avatar immediately in local memory
                        // Note: Avatar upload to server is temporarily disabled due to service conflicts
                        // Avatar will be updated locally but reset on next login
                        System.out.println("Avatar updated locally (will reset on next login)");
                            
                        // Update avatar display immediately
                        SwingUtilities.invokeLater(() -> {
                            try {
                                ByteArrayInputStream bis = new ByteArrayInputStream(data);
                                BufferedImage bImage = ImageIO.read(bis);
                                if (bImage != null) {
                                    ImageIcon Avatar = new ImageIcon(bImage);
                                    imaAvatar.setImage(Avatar);
                                    imaAvatar.repaint();
                                    imaAvatar.revalidate();
                                    System.out.println("Avatar updated locally and displayed");
                                }
                            } catch (IOException ex) {
                                ex.printStackTrace();
                            }
                        });
                        
                        try {
                             sendImageAvatar();
                     } catch (IOException ex) {
                     Logger.getLogger(popMix.class.getName()).log(Level.SEVERE, null, ex);
                   }
                        
        } catch (IOException e) {
            System.err.println(e);
        }
                   }
       }
          }//GEN-LAST:event_imaAvatarMouseClicked
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Xử lý đăng xuất
        handleLogout();
    }    private void handleLogout() {
        try {
            // Temporarily comment out service calls due to import conflicts
            /*
            // Lấy instance của service client
            service.Service serviceInstance = service.Service.getInstance();
            
            // Thông báo server về việc đăng xuất
            if (serviceInstance.getClient() != null && serviceInstance.getClient().connected()) {
                serviceInstance.getClient().emit("user_logout", serviceInstance.getUser().getUserID());
                serviceInstance.getClient().disconnect();
            }
            
            // Reset user data
            serviceInstance.setUser(null);
            */
            
            // Đóng main window hiện tại
            SwingUtilities.getWindowAncestor(this).dispose();
            
            // Mở lại màn hình login
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                        // Tạo instance mới của form login
                        new form.P_Login().setVisible(true);
                    } catch (Exception e) {
                        e.printStackTrace();
                        // Fallback: tạo main window mới nếu không tìm thấy P_Login
                        new main.Main().setVisible(true);
                    }
                }
            });
            
        } catch (Exception e) {
            Logger.getLogger(Menu_Right.class.getName()).log(Level.SEVERE, "Error during logout", e);
            e.printStackTrace();
        }
    }
    
    private boolean isImageFile(File file){ //kiểm tra đuôi file là định dạng image hợp lệ
            String name = file.getName().toLowerCase();
            return name.endsWith(".jpg")||name.endsWith(".png")||name.endsWith(".jpeg")||name.endsWith(".gif");
    }    private void sendImageAvatar() throws IOException{
       // Upload avatar to server using fully qualified Service class name
       Model_Package_Sender data = new Model_Package_Sender();
      
       data.setFromUserID(service.Service.getInstance().getUser().getUserID());
       byte[] bytes = readData();
       if (bytes != null){
           data.setData(bytes);
           data.setFinish(false);
        }else{
           data.setFinish(true);
           
        }
       // Enable avatar upload to server
        service.Service.getInstance().getClient().emit("send_avatar", data.toJsonObject(), new io.socket.client.Ack() {
            @Override
            public void call(Object... os) {
                if(os.length > 0){
                    boolean act = (boolean) os[0];
                    if (act) {
                        try {
                            if(!data.isFinish()){
                               sendImageAvatar();   
                            }else{
                              // Send avatar update finished
                                 System.out.println("Avatar update finished and saved to database");
                                 // Avatar is now saved to database on server
                            }
                        } catch (IOException e) {
                           e.printStackTrace();
                        }
                    } else {
                        System.err.println("Failed to upload avatar to server");
                    }
                
                }
                
            }
        });
        System.out.println("Send avatar data: " + (bytes != null ? bytes.length : 0) + " bytes");
    }
    public synchronized byte[]readData(){
        if(bb.position() != fileSize){
            int max = 1500;
            long length = bb.position() + max >= fileSize ? fileSize - bb.position() : max;
            byte[] someByte = new byte[(int) length];
            splitByteArray(someByte, bb);
            System.out.println(someByte.length);
            return someByte;
        }else{
            return null;
        }
         
    }    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Panel2;
    private swing.ImageAvatar imaAvatar;
    private javax.swing.JButton jButton1;
    private swing.Panel panel1;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
    private ByteBuffer bb;
    private byte[] DataByte;
    private long fileSize; 
}

