/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import event.EventMessage;
import event.PublicEvent;
import model.Model_Message;
import model.Model_Register;

/**
 *
 * @author Admin
 */
public class Register extends javax.swing.JPanel {

    /**
     * Creates new form Register
     */    public Register() {
        initComponents();
        CustomButtonRegistry();
        CustomButtonBackLogin();
        init();
    }    private void CustomButtonRegistry(){
        cmdRegistry.setBackground(new java.awt.Color(104, 88, 219));
        cmdRegistry.setForeground(new java.awt.Color(255, 255, 255));
        cmdRegistry.setText("Đăng ký");
        cmdRegistry.setColorClick(new java.awt.Color(152, 196, 239));
        cmdRegistry.setColorOver(new java.awt.Color(219, 74, 131));
        cmdRegistry.setFillBorder(30);
        cmdRegistry.setFocusable(false);
        cmdRegistry.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        jLabel1.setVisible(false);
    }
    
    private void CustomButtonBackLogin(){
        cmdBackLogin.setContentAreaFilled(false); // Không hiển thị nền
        cmdBackLogin.setBorderPainted(false); // Không hiển thị viền
        cmdBackLogin.setForeground(new java.awt.Color(104, 88, 219)); // Màu tím giống button registry
        cmdBackLogin.setText("Đăng Nhập Ngay");
        cmdBackLogin.setFont(new java.awt.Font("iCiel Mijas", java.awt.Font.BOLD, 14)); // Font đậm
        cmdBackLogin.setFocusable(false);
        cmdBackLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdBackLogin.setOpaque(false); // Đảm bảo button hoàn toàn trong suốt
    }    private void init(){
        CustomTextFields();
    }
    
    private void CustomTextFields(){
        // Tùy chỉnh ô Username
        txtUserName.setOpaque(false); // Nền trong suốt
        txtUserName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(104, 88, 219))); // Chỉ có border dưới
        txtUserName.setBackground(new java.awt.Color(0, 0, 0, 0)); // Nền hoàn toàn trong suốt
        txtUserName.setFont(new java.awt.Font("iCiel Mijas", 0, 14));
        txtUserName.setForeground(new java.awt.Color(60, 60, 60));
        
        // Tùy chỉnh ô Password
        txtPass.setOpaque(false); // Nền trong suốt
        txtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(104, 88, 219))); // Chỉ có border dưới
        txtPass.setBackground(new java.awt.Color(0, 0, 0, 0)); // Nền hoàn toàn trong suốt
        txtPass.setFont(new java.awt.Font("iCiel Mijas", 0, 14));
        txtPass.setForeground(new java.awt.Color(60, 60, 60));
        
        // Tùy chỉnh ô Confirm Password
        txtRepass.setOpaque(false); // Nền trong suốt
        txtRepass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(104, 88, 219))); // Chỉ có border dưới
        txtRepass.setBackground(new java.awt.Color(0, 0, 0, 0)); // Nền hoàn toàn trong suốt
        txtRepass.setFont(new java.awt.Font("iCiel Mijas", 0, 14));
        txtRepass.setForeground(new java.awt.Color(60, 60, 60));
        
        // Tùy chỉnh nút toggle password
        togglePass.setBorder(null);
        togglePass.setContentAreaFilled(false);
        togglePass.setFont(new java.awt.Font("Segoe UI", 0, 14));
        togglePass.setText("*");
        togglePass.setForeground(new java.awt.Color(104, 88, 219));
        togglePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        togglePass.setFocusPainted(false);
        
        // Tùy chỉnh nút toggle confirm password
        toggleRepass.setBorder(null);
        toggleRepass.setContentAreaFilled(false);
        toggleRepass.setFont(new java.awt.Font("Segoe UI", 0, 14));
        toggleRepass.setText("*");
        toggleRepass.setForeground(new java.awt.Color(104, 88, 219));
        toggleRepass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toggleRepass.setFocusPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureBox1 = new swing.PictureBox();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        cmdRegistry = new swing.Button();
        txtUserName = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        txtRepass = new javax.swing.JPasswordField();
        togglePass = new javax.swing.JButton();
        toggleRepass = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmdBackLogin = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/icon/register.png"))); // NOI18N

        cmdRegistry.setFont(new java.awt.Font("iCiel Mijas", 0, 15)); // NOI18N
        cmdRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegistryActionPerformed(evt);
            }
        });

        txtUserName.setBorder(null);

        txtPass.setBorder(null);

        txtRepass.setBorder(null);
        
        togglePass.setText("*");
        togglePass.setBorder(null);
        togglePass.setContentAreaFilled(false);
        togglePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                togglePassActionPerformed(evt);
            }
        });
        
        toggleRepass.setText("*");
        toggleRepass.setBorder(null);
        toggleRepass.setContentAreaFilled(false);
        toggleRepass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleRepassActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(cmdRegistry, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtUserName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtPass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(togglePass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtRepass, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(toggleRepass, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(togglePass, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(txtRepass, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(toggleRepass, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(cmdRegistry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(92, 92, 92))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(togglePass, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtRepass, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(toggleRepass, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cmdRegistry, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addGap(35, 35, 35))
        );

        pictureBox1.add(jLayeredPane1);
        jLayeredPane1.setBounds(620, 200, 300, 250);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        pictureBox1.add(jLabel1);
        jLabel1.setBounds(620, 450, 310, 20);

        cmdBackLogin.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        cmdBackLogin.setContentAreaFilled(false);
        cmdBackLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdBackLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBackLoginActionPerformed(evt);
            }
        });
        pictureBox1.add(cmdBackLogin);
        cmdBackLogin.setBounds(760, 440, 218, 10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pictureBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void togglePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_togglePassActionPerformed
        togglePasswordVisibility(txtPass, togglePass);
    }//GEN-LAST:event_togglePassActionPerformed

    private void toggleRepassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleRepassActionPerformed
        togglePasswordVisibility(txtRepass, toggleRepass);
    }//GEN-LAST:event_toggleRepassActionPerformed

    private void togglePasswordVisibility(javax.swing.JPasswordField passField, javax.swing.JButton toggleBtn) {
        if (passField.getEchoChar() == 0) {
            passField.setEchoChar('•');
            toggleBtn.setText("*");
        } else {
            passField.setEchoChar((char) 0);
            toggleBtn.setText("*");
        }
    }

    private void cmdBackLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackLoginActionPerformed
         PublicEvent.getInstance().getEventLogin().goLogin();
    }//GEN-LAST:event_cmdBackLoginActionPerformed

    private void cmdRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegistryActionPerformed
        String userName = txtUserName.getText().trim();
        String password = String.valueOf(txtPass.getPassword());
        String confirmPassword = String.valueOf(txtRepass.getPassword());
        if(userName.equals("")){
             txtUserName.grabFocus();
        }else if(password.equals("")){
            txtPass.grabFocus();
        }else if(!password.equals(confirmPassword)){
            txtPass.grabFocus();
        }else{
            // Yêu cầu mật khẩu: >10 ký tự, bắt đầu bằng chữ cái, chứa chữ số và dấu gạch nối
            // String pwdPattern = "^(?=.{11,}$)(?=.*\\d)(?=.*-)[A-Za-z][A-Za-z0-9-]*$";
            // if (!password.matches(pwdPattern)) {
            //     jLabel1.setVisible(true);
            //     jLabel1.setText("Mật khẩu phải >10 ký tự, bắt đầu bằng chữ cái, chứa chữ số và dấu '-' ");
            //     txtPass.grabFocus();
            //     return;
            // }
            Model_Register data = new Model_Register(userName, password);
            PublicEvent.getInstance().getEventLogin().Register(data, new EventMessage() {                @Override
                public void callMessage(Model_Message message) {
                    if(!message.isAction()){ //if biến message ko phải true = false
                    jLabel1.setVisible(true);
                    jLabel1.setText(message.getMessage());
                    }else{
                        jLabel1.setText("Đăng ký tài khoản thành công !");                        // Cập nhật Menu_Right với thông tin user mới
                        PublicEvent.getInstance().getEventMenuRight().setImageAvatar(service.Service.getInstance().getUser());
                        PublicEvent.getInstance().getEventMain().initChat();
                    }
                   }
            });
        }
    }//GEN-LAST:event_cmdRegistryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBackLogin;
    private swing.Button cmdRegistry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private swing.PictureBox pictureBox1;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtRepass;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JButton togglePass;
    private javax.swing.JButton toggleRepass;
    // End of variables declaration//GEN-END:variables
}
